<a href="https://colab.research.google.com/github/charite-uwatwembi/MachineLearning-PCA/blob/main/Formative_Assignment_PCA_Charite_Uwatwembi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [12]:
#import necessary package
import numpy as np
import numpy.linalg as eig
#TO DO


In [13]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

In [19]:
 #TO DO:  Insert code here





avg = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)
standardized_data = (data - avg) / std_dev
print(standardized_data)



[[-1.36438208  0.70710678  1.5109662  -0.99186978  0.77802924]
 [ 0.12403473 -1.94454365 -0.13736056  0.77145428 -2.06841919]
 [-0.62017367  0.1767767   0.68680282 -0.99186978  0.20873955]
 [ 1.61245155  0.1767767  -1.78568733  0.33062326  0.20873955]
 [-0.62017367  1.23743687 -0.13736056 -0.77145428  1.00574511]
 [ 0.86824314 -0.35355339 -0.13736056  1.65311631 -0.13283426]]


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [25]:

 #TO DO: insert code here


# Compute the covariance matrix manually
cov_matrix = np.cov(standardized_data, rowvar=False)
print(cov_matrix)


[[ 1.2        -0.42098785 -1.0835838   0.90219291 -0.37000528]
 [-0.42098785  1.2         0.20397003 -0.77149364  1.18751836]
 [-1.0835838   0.20397003  1.2        -0.59947269  0.22208218]
 [ 0.90219291 -0.77149364 -0.59947269  1.2        -0.70017993]
 [-0.37000528  1.18751836  0.22208218 -0.70017993  1.2       ]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [26]:


 #TO DO: Insert code here for eigenvalues, eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[3.80985761e+00 1.73655615e+00 4.94531029e-02 4.74189469e-05
 4.04085720e-01]

Eigenvectors:
[[-0.4640131   0.45182808 -0.70733581  0.28128049 -0.03317471]
 [ 0.45019005  0.48800851  0.29051532  0.6706731  -0.15803498]
 [ 0.37929082 -0.55665017 -0.48462321  0.24186072 -0.5029143 ]
 [-0.4976889   0.03162214  0.36999674 -0.03373724 -0.78311558]
 [ 0.43642295  0.49682965 -0.20861365 -0.64143906 -0.32822489]]


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [27]:
# Determine the order of importance (highest to lowest)
order_of_importance = np.argsort(eigenvalues)[::-1]
print('\nThe order of importance is:\n{}'.format(order_of_importance))

# Utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance]
print('\n\nSorted eigenvalues:\n{}'.format(sorted_eigenvalues))

sorted_eigenvectors = eigenvectors[:, order_of_importance]
print('\n\nThe sorted eigenvector matrix is:\n{}'.format(sorted_eigenvectors))


The order of importance is:
[0 1 4 2 3]


Sorted eigenvalues:
[3.80985761e+00 1.73655615e+00 4.04085720e-01 4.94531029e-02
 4.74189469e-05]


The sorted eigenvector matrix is:
[[-0.4640131   0.45182808 -0.03317471 -0.70733581  0.28128049]
 [ 0.45019005  0.48800851 -0.15803498  0.29051532  0.6706731 ]
 [ 0.37929082 -0.55665017 -0.5029143  -0.48462321  0.24186072]
 [-0.4976889   0.03162214 -0.78311558  0.36999674 -0.03373724]
 [ 0.43642295  0.49682965 -0.32822489 -0.20861365 -0.64143906]]


Question:

1. Why do we order eigen values and eigen vectors?

[Ordering eigenvalues and eigenvectors enables us to prioritize the most significant directions of data variation, with the importance of each eigenvalue reflecting the variance it explains. Sorting them from highest to lowest allows us to identify key components, where the largest eigenvalues correspond to the most important directions or principal components capturing the most variance. This ordering facilitates dimensionality reduction in techniques like Principal Component Analysis (PCA), where we project the data onto the top principal components, simplifying it while retaining maximal information. Moreover, ordered eigenvalues and their corresponding eigenvectors aid in interpreting the structure and patterns within the data, streamlining data interpretation processes.]

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

[No, In eigenvalue-eigenvector analysis, we prioritize the highest eigenvalues over the lowest ones because they represent the directions in the data space where the most variance occurs. These directions capture the most significant patterns or structures in the data, making them crucial for tasks like Principal Component Analysis (PCA) where dimensionality reduction aims to retain the most informative features. By focusing on the highest eigenvalues, we extract the most important components of the data for analysis, interpretation, and modeling purposes.]


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [35]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
sorted_eigenvalues = [3.80985761e+00, 1.73655615e+00, 4.04085720e-01, 4.94531029e-02, 4.74189469e-05]

total_variance = sum(sorted_eigenvalues)

explained_variance = [(eigval / total_variance) * 100 for eigval in sorted_eigenvalues]

explained_variance = ["{:.2f}%".format(value) for value in explained_variance]

print(explained_variance)


['63.50%', '28.94%', '6.73%', '0.82%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [37]:
k = 2 # select the number of principal components


reduced_data = sorted_eigenvectors[:, order_of_importance[:k]]
reduced_data = np.matmul(standardized_data, reduced_data)

In [33]:
print(reduced_data)

[[ 2.3577116  -0.75728867]
 [-2.27171739 -1.81970663]
 [ 1.21259114 -0.50390931]
 [-1.41935914  1.9229856 ]
 [ 1.61562536  0.87541857]
 [-1.49485157  0.28250044]]


In [38]:
print("Shape of reduced data:", reduced_data.shape)

Shape of reduced data: (6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations
[insert answer here]


**Positive Effects: **

1. **Dimensionality Reduction:** PCA effectively reduces the dimensionality of the data by transforming it into a new set of variables called principal components. This reduction simplifies the dataset, making it easier to visualize, analyze, and interpret, while still retaining most of the original information. It helps in dealing with high-dimensional data, improving computational efficiency, and facilitating data exploration.

2. **Feature Extraction:** PCA identifies the most important features or patterns in the data by capturing the directions of maximum variance. These principal components are orthogonal to each other, meaning they represent independent sources of variation. By focusing on these components, PCA enables feature extraction, allowing for the removal of noise or irrelevant features and emphasizing the most significant ones. This feature extraction process aids in improving the performance of machine learning models by focusing on the most informative aspects of the data.

**Negative Effects:**

1. **Loss of Interpretability:** While PCA simplifies the data by reducing its dimensionality, it may also lead to a loss of interpretability. The transformed principal components are linear combinations of the original features, making it challenging to interpret them directly in terms of the original variables. This loss of interpretability can hinder the understanding of underlying patterns or relationships in the data, especially when trying to communicate findings to stakeholders or domain experts.

2. **Assumption of Linearity:** PCA assumes that the underlying relationships in the data are linear. However, if the data exhibits nonlinear relationships, PCA may not effectively capture all the variations, leading to suboptimal results. In such cases, nonlinear dimensionality reduction techniques like t-distributed Stochastic Neighbor Embedding (t-SNE) or Isomap may be more appropriate. Therefore, it's essential to assess whether the linear assumption holds true for the dataset before applying PCA to avoid misinterpretations or inaccuracies in the results.